
version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "${PORT}:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Caso necessite de um banco de dados no futuro, considere utilizar
  # as variáveis de ambiente do EasyPanel:
  # db:
  #   image: postgres:14-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_DB=${DB_DATABASE}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# Caso habilite o serviço de banco de dados
# volumes:
#   postgres_data:
