// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qouvlhomajrffblnzegr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvdXZsaG9tYWpyZmZibG56ZWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3NDg4ODMsImV4cCI6MjA0ODMyNDg4M30.rYs9rZc4pyNLOOU_N5N6XNQAGJDg5ljNt7B-ZdaRV3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);