// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uunuonapovtyuwtelrng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1bnVvbmFwb3Z0eXV3dGVscm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODA0MTEsImV4cCI6MjA2MDE1NjQxMX0.Cmb1APZ-biMXqcthgVzupZXDeitESrbUwcuA9qpFQ_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);